---

- name: Debian, install espeakup
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - espeak
    - libespeak-dev
    - espeakup
  when: ansible_os_family == "Debian"

- name: Copy speakup.conf to /etc/modules-load.d
  copy:
    src: speakup.conf
    dest: /etc/modules-load.d
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == "Debian"

- name: Load speakup_soft for this session
  modprobe:
    name: speakup_soft
    state: present
  when: ansible_os_family == "Debian"

- name: Enable espeakup service
  service:
    name: espeakup
    enabled: yes
  when: ansible_os_family == "Debian"

- name: Start espeakup service
  service:
    name: espeakup
    state: started
  when: ansible_os_family == "Debian"

