---


- name: Debian, install espeakup
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - espeak
    - libespeak-dev
    - espeakup
  when: ansible_os_family == "Debian"

- name: Add speakup_soft line to /etc/modules-load.d/modules.conf
  command: echo -e "speakup_soft\n" >> /etc/modules-load.d/modules.conf
  when: ansible_os_family == "Debian"

