---

# Localisation
locale: en_GB
keymap: uk


# User variables
default_user: alarm


# speech-dispatcher
AudioOutputMethod: libao



skip_braille: true
skip_devtools: false
skip_fenrir: true
skip_sound: true
skip_user: true
skip_yaourt: false

