---

- name: Start of tasks from main.yml
  debug: msg="Start of tasks from main.yml"

- name: Include tasks from devtools.yml
  include_tasks: devtools.yml
  tags: [devtools]
  when: not skip_devtools

- name: Include tasks from espeakup.yml
  include_tasks: espeakup.yml
  tags: [espeakup]
  when: not skip_espeakup


- name: Include tasks from speechd.yml
  include_tasks: speechd.yml
  tags: [speechd]
  when: not skip_speechd

- name: Include tasks from mate.yml
  include_tasks: mate.yml
  tags: [mate]
  when: (not skip_desktop
        and desktop == "mate")


- name: Include tasks from orca.yml
  include_tasks: orca.yml
  tags: [orca]
  when: not skip_orca

- name: End of tasks from main.yml
  debug: msg="End of tasks from main.yml"




