---

- name: Debian, install speech-dispatcher
  apt:
    name: "{{ item }}"
  with_items:
    - libao-common
    - speech-dispatcher
  when: ansible_os_family == "Debian"


- name: Debian, install speechd.conf template
  template:
    src: speechd.conf.j2
    dest: /etc/speech-dispatcher/speechd.conf
    backup: yes
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == "Debian"

