---

#
# Fail if architecture is 'aarch64' (64-bit Raspberry Pi with 64-bit OS).
#
# Because no 64-bit userland code is currently available. The userland
# code includes the vchiq process for queueing speech into the
# Raspberry Pi GPU.
#

- name: Fail if architecture is aarch64
  fail:
    msg: "No point in installing speech-dispatcher on 64-bit OS. No userland code available."
  when: ansible_architecture == "aarch64"
  tags: [speechd]

- name: Debian, install speech-dispatcher
  apt:
    name: "{{ item }}"
  with_items:
    - libao-common
    - speech-dispatcher
  when: ansible_distribution == "Debian"
  tags: [speechd]


- name: Debian, install speechd.conf template
  template:
    src: speechd.conf.j2
    dest: /etc/speech-dispatcher/speechd.conf
    backup: yes
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == "Debian"
  tags: [speechd]

