---
## braille.yml

- name: Arch, Install brltty-minimal dependencies
  pacman:
    name: icu,liblouis
    state: latest
    update_cache: yes
  when: ansible_distribution == "Archlinux"
  tags: [braille]


- name: Arch, install brltty-minimal from the AUR
  aur:
    name: brltty-minimal
    user: "{{ default_user }}"
    dir: /tmp
  when: ansible_distribution == "Archlinux"
  tags: [braille]

- name: Debian, install brltty
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  whith_items:
    - brltty
  when: ansible_distribution == "Debian"
  tags: [braille]


- name: Set accessibility switches
  gsetting:
    user: "{{ default_user }}"
    key: "{{ item }}"
    value: true
  with_items:
    - org.mate.interface.accessibility
    - org.gnome.desktop.a11y.applications.screen-reader-enabled
  when: ansible_distribution == "Debian"
  tags: [braille]




