---
## console.yml

- name: Import tasks from espeakup.yml
  import_tasks: espeakup.yml
  when:
    - console_screen_reader == "speakup"
  tags:
    - console

- name: Import tasks from fenrir.yml
  import_tasks: fenrir.yml
  when:
    - console_screen_reader == "fenrir"
  tags:
    - console

- name: Import tasks from emacs.yml
  import_tasks: emacs.yml
  when:
    - not skip_emacspeak
  tags:
    console

- name: Import tasks from emacspeak.yml
  import_tasks: emacspeak.yml
  when:
    - not skip_emacspeak
  tags:
    - console

