---
## espeakup.yml

#
# Fail if architecture is 'aarch64' (64-bit Raspberry Pi with 64-bit OS).
#
# Because no 64-bit userland code is currently available. The userland
# code includes the vchiq process for queueing speech into the
# Raspberry Pi GPU.
#

- name: Fail if architecture is aarch64
  fail:
    msg: "No point in installing speakup/espeakup on 64-bit OS. No userland code available."
  when: ansible_architecture == "aarch64"
  tags: [espeakup]

- name: Debian, install espeakup
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - espeak
    - libespeak-dev
    - espeakup
  when: (ansible_distribution == "Debian"
        and console_screen_reader == "speakup")
  tags: [espeakup]

- name: Copy speakup.conf to /etc/modules-load.d
  copy:
    src: speakup.conf
    dest: /etc/modules-load.d
    owner: root
    group: root
    mode: 0644
  when: (ansible_distribution == "Debian"
        and console_screen_reader == "speakup")
  tags: [espeakup]

- name: Load speakup_soft for this session
  modprobe:
    name: speakup_soft
    state: present
  when: ansible_distribution == "Debian"
  tags: [espeakup]

- name: Enable espeakup service
  service:
    name: espeakup
    enabled: yes
  when: ansible_distribution == "Debian"
  tags: [espeakup]

- name: Start espeakup service
  service:
    name: espeakup
    state: started
  when: ansible_distribution == "Debian"
  tags: [espeakup]

