---
## fenrir.yml

- name: Start of tasks from fenrir.yml
  debug:
    msg: "Start of tasks from fenrir.yml"
  tags:
    - fenrir


- name: Fail if architecture is aarch64 on a Raspberry Pi
  fail:
    msg: "No point in installing fenrir on 64-bit OS. No userland code available."
  when:
    - ansible_architecture == "aarch64"
    - is defined raspberry_pi
  tags:
    - fenrir

#
# The host needs to be running Python 3 in order to run
# the Fenrir screen reader
#

- name: Test which version of Python is symlinked
  shell: python --version
  register: python_version
  tags:
    - fenrir


- name: Fail if not running Python 3
  fail:
    msg: "Fenrir needs Python 3"
  when:
    - python_version.stdout.find('Python 3') == -1
  tags:
    - fenrir

- name: Arch, install pip3
  pacman:
    name: python-pip
    state: latest
    update_cache: yes
  when:
    - ansible_distribution == "Archlinux"
  tags:
    - fenrir

- name: Debian, install pip3
  apt:
    name: python3-pip
    state: latest
    update_cache: yes
  when:
    - ansible_distribution == "Debian"
  tags:
    - fenrir

- name: Arch, install Fenrir dependencies
  pacman:
    name: dbus
    state: latest
    update_cache: yes
  when:
    - ansible_distribution == "Archlinux"
  tags:
    - fenrir

- name: Debian, install Fenrir dependencies
  apt:
    name: dbus,libdbus-glib-1-dev
    state: latest
    update_cache: yes
  when:
    - ansible_distribution == "Debian"
  tags:
    - fenrir


- name: Install Fenrir screen reader from pip
  pip:
    name: fenrir-screenreader
    state: present
  when:
    - ansible_distribution in ["Archlinux", "Debian"]
  tags:
    - fenrir

- name: End of tasks from fenrir.yml
  debug:
    msg: "End of tasks from fenrir.yml"
  tags:
    - fenrir

