---
## i3.yml

#
# Debug msg if architecture is 'aarch64' (64-bit Raspberry Pi with 64-bit OS).
#
# Because no 64-bit userland code is currently available. The userland
# code includes the vchiq process for queueing speech into the
# Raspberry Pi GPU.
#

- name: Warn if architecture is aarch64
  debug: msg="No point in installing desktop on 64-bit OS. No userland code available."
  when:
    - ansible_architecture == "aarch64"
  tags:
    - desktop

- name: Arch, install i3 desktop
  pacman:
    name: i3
    state: latest
    update_cache: yes
  when:
    - ansible_distribution == "Archlinux"
  tags:
    - desktop

- name: Debian, install i3 desktop
  apt:
    name: i3
    state: latest
    update_cache: yes
  when:
    - ansible_distribution == "Debian"
  tags:
    - desktop

