---
## main.yml

- name: Start of tasks from main.yml
  debug:
    msg: "Start of tasks from main.yml"

- name: import tasks from devtools.yml
  import_tasks: devtools.yml
  when:
    - not skip_devtools
  tags:
    - devtools

- name: import tasks from yaourt.yml
  import_tasks: yaourt.yml
  when:
    - ansible_distribution == "Archlinux"
    - not skip_yaourt
  tags:
    - yaourt

- name: import tasks from sound.yml
  import_tasks: sound.yml
  when:
    - not skip_sound
  tags:
    - sound

- name: import tasks from user.yml
  import_tasks: user.yml
  when:
    - not skip_user
  tags:
    - user

- name: import tasks from speechd.yml
  import_tasks: speechd.yml
  when:
    - not skip_speechd
  tags:
    - speechd


#
# emacs-nox is installed in emacs.yml but same tasks are imported
# in console.yml as a dependency of emacspeak
#

- name: import tasks from emacs.yml
  import_tasks: emacs.yml
  when:
    - not skip_emacs
  tags:
    - emacs

- name: import tasks from console.yml
  import_tasks: console.yml
  when:
    - not skip_console
  tags:
    - console


- name: import tasks from desktop.yml
  import_tasks: desktop.yml
  when:
    - not skip_desktop
  tags:
    - desktop

- name: import tasks from braille.yml
  import_tasks: braille.yml
  when:
    - not skip_braille
  tags:
    - braille

- name: import tasks from extras.yml
  import_tasks: extras.yml
  when:
    - not skip_extras
  tags:
    - extras

- name: End of tasks from main.yml
  debug:
    msg: "End of tasks from main.yml"
