---
## mate.yml

#
# Debug msg if architecture is 'aarch64' (64-bit Raspberry Pi with 64-bit OS).
#
# Because no 64-bit userland code is currently available. The userland
# code includes the vchiq process for queueing speech into the
# Raspberry Pi GPU.
#

- name: Warn if architecture is aarch64
  debug: msg="No point in installing desktop on 64-bit OS. No userland code available."
  when: ansible_architecture == "aarch64"
  tags:
    - desktop

- name: Arch, install Mate desktop
  pacman:
    name: mate,mate-extra
    state: latest
    update_cache: yes
  when: (ansible_distribution == "Archlinux"
        and desktop == "mate")
  tags:
    - desktop

- name: Debian, install Mate desktop
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - mate-core
    - mate-desktop-environment
    - lightdm
  when: (ansible_distribution == "Debian"
        and desktop == "mate")
  tags:
    - desktop

- name: Fix lightdm config
  command: sed -i 's|^#\(greeter-wrapper=\)|\1/usr/bin/orca-dm-wrapper|' /etc/lightdm/lightdm.conf
  when: (ansible_distribution == "Debian"
        and desktop == "mate")
  tags:
    - desktop

- name: Install orca-dm-wrapper
  file:
    src: orca-dm-wrapper
    dest: /usr/bin/orca-dm-wrapper
    owner: root
    group: root
    mode: 0755
  when: desktop == "mate"
  tags:
    - desktop

- name: Install new lightdm.conf
  file:
    src: lightdm.conf
    dest: /etc/lightdm/lightdm.conf
    owner: root
    group: root
    mode: 0664
  when: desktop == "mate"
  tags:
    - desktop

