---
## orca.yml


#
# Fail if architecture is 'aarch64' (64-bit Raspberry Pi with 64-bit OS).
#
# Because no 64-bit userland code is currently available. The userland
# code includes the vchiq process for queueing speech into the
# Raspberry Pi GPU.
#

- name: Fail if architecture is aarch64
  fail:
    msg: "No point in installing Orca on 64-bit OS. No userland code available."
  when:
    - ansible_architecture == "aarch64"
    - is defined raspberry_pi
  tags:
    - orca

- name: Arch, install Orca
  pacman:
    name: orca
    update_cache: yes
    state: latest
  when:
    - ansible_distribution == "Archlinux"
  tags:
    - orca

- name: Debian, install Orca screen reader
  apt:
    name: gnome-orca
    state: latest
    update_cache: yes
  when:
    - ansible_distribution == "Debian"
  tags:
    - orca




